using Microsoft.AspNetCore.Mvc;
using UserManagement.Api.Models;

namespace UserManagement.Api.Controllers
{
    /// <summary>
    /// Handles CRUD operations for User entities.
    /// This week's implementation uses an in-memory list.
    /// Database persistence (EF Core) will be introduced in Week 3.
    /// </summary>
    [ApiController]
    [Route("api/[controller]")]
    public class UsersController : ControllerBase
    {
        // In-memory "database" for now. Static so data survives across requests
        // (but resets when the app restarts). Will be replaced by EF Core later.
        private static readonly List<User> _users = new()
        {
            new User { Id = 1, FirstName = "Ali", LastName = "Khan", Email = "ali.khan@example.com" },
            new User { Id = 2, FirstName = "Sara", LastName = "Ahmed", Email = "sara.ahmed@example.com" },
            new User { Id = 3, FirstName = "Bilal", LastName = "Hassan", Email = "bilal.hassan@example.com" }
        };

        // Tracks the next id to assign. Starts after the seeded users above.
        private static int _nextId = 4;

        /// <summary>
        /// Gets a single user by id.
        /// </summary>
        [HttpGet("{id:int}")]
        public ActionResult<User> GetUserById(int id)
        {
            var user = _users.FirstOrDefault(u => u.Id == id);

            if (user is null)
            {
                return NotFound($"User with id {id} was not found.");
            }

            return Ok(user);
        }

        /// <summary>
        /// Gets all users.
        /// </summary>
        [HttpGet]
        public ActionResult<IEnumerable<User>> GetAllUsers()
        {
            return Ok(_users);
        }

        /// <summary>
        /// Creates a new user. The id is always generated by the server.
        /// </summary>
        [HttpPost]
        public ActionResult<User> CreateUser([FromBody] CreateUserDto newUserDto)
        {
            var newUser = new User
            {
                Id = _nextId++, // server-generated id
                FirstName = newUserDto.FirstName,
                LastName = newUserDto.LastName,
                Email = newUserDto.Email
            };

            _users.Add(newUser);

            return CreatedAtAction(nameof(GetUserById), new { id = newUser.Id }, newUser);
        }

        /// <summary>
        /// Updates an existing user by id.
        /// </summary>
        [HttpPut("{id:int}")]
        public IActionResult UpdateUser(int id, [FromBody] UpdateUserDto updatedUserDto)
        {
            var existingUser = _users.FirstOrDefault(u => u.Id == id);

            if (existingUser is null)
            {
                return NotFound($"User with id {id} was not found.");
            }

            existingUser.FirstName = updatedUserDto.FirstName;
            existingUser.LastName = updatedUserDto.LastName;
            existingUser.Email = updatedUserDto.Email;

            return NoContent();
        }

        /// <summary>
        /// Deletes a user by id.
        /// </summary>
        [HttpDelete("{id:int}")]
        public IActionResult DeleteUser(int id)
        {
            var existingUser = _users.FirstOrDefault(u => u.Id == id);

            if (existingUser is null)
            {
                return NotFound($"User with id {id} was not found.");
            }

            _users.Remove(existingUser);

            return NoContent();
        }
    }
}